###########################################################################
#
# Generated by : Version 10.1 Build 153 11/29/2010 SJ Web Edition
#
# Project      : timetag
# Revision     : testingigo_all
#
# Date         : Sat Feb 12 15:33:58 EST 2011
#
###########################################################################
 
 
# WARNING: Expected ENABLE_CLOCK_LATENCY to be set to 'ON', but it is set to 'OFF'
#          In SDC, create_generated_clock auto-generates clock latency
#
# ------------------------------------------
#
# Create generated clocks based on PLLs
derive_pll_clocks -use_tan_name
#
# ------------------------------------------
# WARNING: Global Fmax translated to derive_clocks. Behavior is not identical
if {![info exist ::qsta_message_posted]} {
    post_message -type warning "Original Global Fmax translated from QSF using derive_clocks"
    set ::qsta_message_posted 1
}
derive_clocks -period "48 MHz"
#


# Original Clock Setting Name: ext_clk
create_clock -period "33.333 ns" \
             -name {ext_clk} {ext_clk}
# ---------------------------------------------


# Original Clock Setting Name: fx2_clk
create_clock -period "20.833 ns" \
             -name {fx2_clk} {fx2_clk}
# ---------------------------------------------

# ** Clock Latency
#    -------------

# ** Clock Uncertainty
#    -----------------

# ** Multicycles
#    -----------
# ** Cuts
#    ----

# ** Input/Output Delays
#    -------------------




# ** Tpd requirements
#    ----------------

# ** Setup/Hold Relationships
#    ------------------------

# ** Tsu/Th requirements
#    -------------------


# ** Tco/MinTco requirements
#    -----------------------



# ---------------------------------------------
# The following clock group is added to try to 
# match the behavior of:
#   CUT_OFF_PATHS_BETWEEN_CLOCK_DOMAINS = ON
# ---------------------------------------------

set_clock_groups -asynchronous \
                 -group { \
                       fx2_clk \
                        } \
                 -group { \
                       altpll0:b2v_inst2|altpll:altpll_component|_clk0 \
                       ext_clk \
                        } \

# ---------------------------------------------

