###########################################################################
#
# Generated by : Version 9.0 Build 235 06/17/2009 Service Pack 2 SJ Web Edition
#
# Project      : testingigo_all
# Revision     : testingigo_all
#
# Date         : Thu Oct 22 5:37:01 AM Eastern Daylight Time 2009
#
###########################################################################
 
 
# WARNING: Expected ENABLE_CLOCK_LATENCY to be set to 'ON', but it is set to 'OFF'
#          In SDC, create_generated_clock auto-generates clock latency
#
# ------------------------------------------
#
# Create generated clocks based on PLLs
derive_pll_clocks -use_tan_name
#
# ------------------------------------------
# WARNING: Global Fmax translated to derive_clocks. Behavior is not identical
if {![info exist ::qsta_message_posted]} {
    post_message -type warning "Original Global Fmax translated from QSF using derive_clocks"
    set ::qsta_message_posted 1
}
derive_clocks -period "100 MHz"
#


# Original Clock Setting Name: FX2_CLK
create_clock -period "13.157 ns" \
             -name {FX2_CLK} {FX2_CLK}
# ---------------------------------------------

# ** Clock Latency
#    -------------

# ** Clock Uncertainty
#    -----------------

# ** Multicycles
#    -----------
# ** Cuts
#    ----

# ** Input/Output Delays
#    -------------------




# ** Tpd requirements
#    ----------------

# ** Setup/Hold Relationships
#    ------------------------

# ** Tsu/Th requirements
#    -------------------


# ** Tco/MinTco requirements
#    -----------------------

#
# Entity Specific Timing Assignments found in
# the Timing Analyzer Settings report panel
#
set_false_path -from [get_keepers {*dcfifo_ekj1*|delayed_wrptr_g[*]}] -to [get_keepers {*dcfifo_ekj1*|*rs_dgwp|*dffpipe7|dffe8a[*]}]
set_false_path -from [get_keepers {*dcfifo_ekj1*|rdptr_g[*]}] -to [get_keepers {*dcfifo_ekj1*|*ws_dgrp|*dffpipe10|dffe11a[*]}]


# ---------------------------------------------

